apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: webapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: 151660158095.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-webapp:webapplication
        ports:
        - containerPort: 8080
        env:
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "10.244.0.6"
        - name: APP_COLOR
          value: "blue"
      imagePullSecrets:
      - name: regcred
